/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'totalRatings' : IDL.Nat,
  'latitude' : IDL.Opt(IDL.Float64),
  'yearsOfExperience' : IDL.Opt(IDL.Nat),
  'ratingsSum' : IDL.Nat,
  'userId' : IDL.Principal,
  'profileImage' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'role' : IDL.Opt(IDL.Text),
  'longitude' : IDL.Opt(IDL.Float64),
  'address' : IDL.Opt(IDL.Text),
  'specialties' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'location' : IDL.Text,
  'verificationStatus' : IDL.Opt(IDL.Text),
});
export const Part = IDL.Record({
  'id' : IDL.Text,
  'inStock' : IDL.Bool,
  'isVerifiedSeller' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sellerName' : IDL.Text,
  'category' : IDL.Text,
  'priceNGN' : IDL.Nat,
});
export const Mechanic = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'isAvailable' : IDL.Bool,
  'specialty' : IDL.Text,
  'distanceKm' : IDL.Float64,
  'rating' : IDL.Float64,
});
export const Time = IDL.Int;
export const Booking = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  }),
  'serviceType' : IDL.Text,
  'scheduledDate' : IDL.Text,
  'scheduledTime' : IDL.Text,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'mechanicId' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
});
export const ServiceRequest = IDL.Record({
  'id' : IDL.Text,
  'customerName' : IDL.Text,
  'status' : IDL.Variant({
    'on_the_way' : IDL.Null,
    'cancelled' : IDL.Null,
    'arrived' : IDL.Null,
    'completed' : IDL.Null,
    'approved' : IDL.Null,
    'accepted' : IDL.Null,
    'searching' : IDL.Null,
    'price_sent' : IDL.Null,
  }),
  'latitude' : IDL.Opt(IDL.Float64),
  'serviceType' : IDL.Text,
  'issueDescription' : IDL.Text,
  'mechanicRating' : IDL.Opt(IDL.Nat),
  'createdAt' : Time,
  'customerRating' : IDL.Opt(IDL.Nat),
  'cancelledBy' : IDL.Opt(IDL.Text),
  'mechanicId' : IDL.Opt(IDL.Principal),
  'longitude' : IDL.Opt(IDL.Float64),
  'address' : IDL.Opt(IDL.Text),
  'mechanicName' : IDL.Opt(IDL.Text),
  'customerId' : IDL.Principal,
  'cancelReason' : IDL.Opt(IDL.Text),
  'price' : IDL.Opt(IDL.Nat),
  'location' : IDL.Text,
});
export const ChatMessage = IDL.Record({
  'id' : IDL.Text,
  'requestId' : IDL.Text,
  'createdAt' : Time,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'senderRole' : IDL.Text,
  'senderId' : IDL.Principal,
});
export const Review = IDL.Record({
  'id' : IDL.Text,
  'userId' : IDL.Principal,
  'text' : IDL.Text,
  'mechanicId' : IDL.Text,
  'timestamp' : Time,
  'rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptServiceRequest' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelServiceRequest' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'completeJob' : IDL.Func([IDL.Text], [], []),
  'createBooking' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
      [IDL.Text],
      [],
    ),
  'createServiceRequest' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Float64),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Text],
      [],
    ),
  'customerRespondToPrice' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'getAllMechanics' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getAllParts' : IDL.Func([], [IDL.Vec(Part)], ['query']),
  'getAvailableMechanics' : IDL.Func([], [IDL.Vec(Mechanic)], ['query']),
  'getBooking' : IDL.Func([IDL.Text], [Booking], ['query']),
  'getCallerUserAppRole' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerActiveRequest' : IDL.Func(
      [],
      [IDL.Opt(ServiceRequest)],
      ['query'],
    ),
  'getCustomerCompletedRequests' : IDL.Func(
      [],
      [IDL.Vec(ServiceRequest)],
      ['query'],
    ),
  'getMechanic' : IDL.Func([IDL.Text], [Mechanic], ['query']),
  'getMechanicActiveJob' : IDL.Func([], [IDL.Opt(ServiceRequest)], ['query']),
  'getMechanicCompletedJobs' : IDL.Func(
      [],
      [IDL.Vec(ServiceRequest)],
      ['query'],
    ),
  'getMechanicPublicProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
  'getPart' : IDL.Func([IDL.Text], [Part], ['query']),
  'getReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
  'getSearchingRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
  'getServiceRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
  'getUserBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markMessagesRead' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserAppRole' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedData' : IDL.Func([], [], []),
  'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'submitRating' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'submitServicePrice' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateBookingStatus' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'cancelled' : IDL.Null,
          'pending' : IDL.Null,
          'completed' : IDL.Null,
          'confirmed' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'updateMechanicVerificationStatus' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [],
      [],
    ),
  'updateServiceRequest' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Variant({ 'price_sent' : IDL.Null })],
      [],
      [],
    ),
  'updateServiceRequestStatus' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'on_the_way' : IDL.Null,
          'arrived' : IDL.Null,
          'completed' : IDL.Null,
          'accepted' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'updateUserProfile' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
      ],
      [UserProfile],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'totalRatings' : IDL.Nat,
    'latitude' : IDL.Opt(IDL.Float64),
    'yearsOfExperience' : IDL.Opt(IDL.Nat),
    'ratingsSum' : IDL.Nat,
    'userId' : IDL.Principal,
    'profileImage' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'role' : IDL.Opt(IDL.Text),
    'longitude' : IDL.Opt(IDL.Float64),
    'address' : IDL.Opt(IDL.Text),
    'specialties' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'location' : IDL.Text,
    'verificationStatus' : IDL.Opt(IDL.Text),
  });
  const Part = IDL.Record({
    'id' : IDL.Text,
    'inStock' : IDL.Bool,
    'isVerifiedSeller' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sellerName' : IDL.Text,
    'category' : IDL.Text,
    'priceNGN' : IDL.Nat,
  });
  const Mechanic = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'isAvailable' : IDL.Bool,
    'specialty' : IDL.Text,
    'distanceKm' : IDL.Float64,
    'rating' : IDL.Float64,
  });
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'cancelled' : IDL.Null,
      'pending' : IDL.Null,
      'completed' : IDL.Null,
      'confirmed' : IDL.Null,
    }),
    'serviceType' : IDL.Text,
    'scheduledDate' : IDL.Text,
    'scheduledTime' : IDL.Text,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'mechanicId' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
  });
  const ServiceRequest = IDL.Record({
    'id' : IDL.Text,
    'customerName' : IDL.Text,
    'status' : IDL.Variant({
      'on_the_way' : IDL.Null,
      'cancelled' : IDL.Null,
      'arrived' : IDL.Null,
      'completed' : IDL.Null,
      'approved' : IDL.Null,
      'accepted' : IDL.Null,
      'searching' : IDL.Null,
      'price_sent' : IDL.Null,
    }),
    'latitude' : IDL.Opt(IDL.Float64),
    'serviceType' : IDL.Text,
    'issueDescription' : IDL.Text,
    'mechanicRating' : IDL.Opt(IDL.Nat),
    'createdAt' : Time,
    'customerRating' : IDL.Opt(IDL.Nat),
    'cancelledBy' : IDL.Opt(IDL.Text),
    'mechanicId' : IDL.Opt(IDL.Principal),
    'longitude' : IDL.Opt(IDL.Float64),
    'address' : IDL.Opt(IDL.Text),
    'mechanicName' : IDL.Opt(IDL.Text),
    'customerId' : IDL.Principal,
    'cancelReason' : IDL.Opt(IDL.Text),
    'price' : IDL.Opt(IDL.Nat),
    'location' : IDL.Text,
  });
  const ChatMessage = IDL.Record({
    'id' : IDL.Text,
    'requestId' : IDL.Text,
    'createdAt' : Time,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'senderRole' : IDL.Text,
    'senderId' : IDL.Principal,
  });
  const Review = IDL.Record({
    'id' : IDL.Text,
    'userId' : IDL.Principal,
    'text' : IDL.Text,
    'mechanicId' : IDL.Text,
    'timestamp' : Time,
    'rating' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptServiceRequest' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelServiceRequest' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'completeJob' : IDL.Func([IDL.Text], [], []),
    'createBooking' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Opt(IDL.Text)],
        [IDL.Text],
        [],
      ),
    'createServiceRequest' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Float64),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Text],
        [],
      ),
    'customerRespondToPrice' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'getAllMechanics' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getAllParts' : IDL.Func([], [IDL.Vec(Part)], ['query']),
    'getAvailableMechanics' : IDL.Func([], [IDL.Vec(Mechanic)], ['query']),
    'getBooking' : IDL.Func([IDL.Text], [Booking], ['query']),
    'getCallerUserAppRole' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerActiveRequest' : IDL.Func(
        [],
        [IDL.Opt(ServiceRequest)],
        ['query'],
      ),
    'getCustomerCompletedRequests' : IDL.Func(
        [],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getMechanic' : IDL.Func([IDL.Text], [Mechanic], ['query']),
    'getMechanicActiveJob' : IDL.Func([], [IDL.Opt(ServiceRequest)], ['query']),
    'getMechanicCompletedJobs' : IDL.Func(
        [],
        [IDL.Vec(ServiceRequest)],
        ['query'],
      ),
    'getMechanicPublicProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(ChatMessage)], ['query']),
    'getPart' : IDL.Func([IDL.Text], [Part], ['query']),
    'getReviews' : IDL.Func([IDL.Text], [IDL.Vec(Review)], ['query']),
    'getSearchingRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
    'getServiceRequests' : IDL.Func([], [IDL.Vec(ServiceRequest)], ['query']),
    'getUserBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markMessagesRead' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserAppRole' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedData' : IDL.Func([], [], []),
    'sendMessage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'submitRating' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'submitServicePrice' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateBookingStatus' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'cancelled' : IDL.Null,
            'pending' : IDL.Null,
            'completed' : IDL.Null,
            'confirmed' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'updateMechanicVerificationStatus' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [],
        [],
      ),
    'updateServiceRequest' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Variant({ 'price_sent' : IDL.Null })],
        [],
        [],
      ),
    'updateServiceRequestStatus' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'on_the_way' : IDL.Null,
            'arrived' : IDL.Null,
            'completed' : IDL.Null,
            'accepted' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'updateUserProfile' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
        ],
        [UserProfile],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };