/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : string,
  'status' : { 'cancelled' : null } |
    { 'pending' : null } |
    { 'completed' : null } |
    { 'confirmed' : null },
  'serviceType' : string,
  'scheduledDate' : string,
  'scheduledTime' : string,
  'userId' : Principal,
  'createdAt' : Time,
  'mechanicId' : string,
  'notes' : [] | [string],
}
export interface ChatMessage {
  'id' : string,
  'requestId' : string,
  'senderId' : Principal,
  'senderRole' : string,
  'message' : string,
  'isRead' : boolean,
  'createdAt' : Time,
}
export interface Mechanic {
  'id' : string,
  'name' : string,
  'isAvailable' : boolean,
  'specialty' : string,
  'distanceKm' : number,
  'rating' : number,
}
export interface Part {
  'id' : string,
  'inStock' : boolean,
  'isVerifiedSeller' : boolean,
  'name' : string,
  'description' : string,
  'sellerName' : string,
  'category' : string,
  'priceNGN' : bigint,
}
export interface Review {
  'id' : string,
  'userId' : Principal,
  'text' : string,
  'mechanicId' : string,
  'timestamp' : Time,
  'rating' : bigint,
}
export interface ServiceRequest {
  'id' : string,
  'customerName' : string,
  'status' : { 'on_the_way' : null } |
    { 'arrived' : null } |
    { 'completed' : null } |
    { 'accepted' : null } |
    { 'searching' : null } |
    { 'price_sent' : null } |
    { 'approved' : null } |
    { 'cancelled' : null },
  'serviceType' : string,
  'issueDescription' : string,
  'createdAt' : Time,
  'mechanicId' : [] | [Principal],
  'mechanicName' : [] | [string],
  'price' : [] | [bigint],
  'cancelledBy' : [] | [string],
  'cancelReason' : [] | [string],
  'customerId' : Principal,
  'location' : string,
  'latitude' : [] | [number],
  'longitude' : [] | [number],
  'address' : [] | [string],
  'customerRating' : [] | [bigint],
  'mechanicRating' : [] | [bigint],
}
export type Time = bigint;
export interface UserProfile {
  'userId' : Principal,
  'name' : string,
  'phone' : string,
  'location' : string,
  'latitude' : [] | [number],
  'longitude' : [] | [number],
  'address' : [] | [string],
  'profileImage' : [] | [string],
  'role' : [] | [string],
  'yearsOfExperience' : [] | [bigint],
  'specialties' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptServiceRequest' : ActorMethod<[string, string], undefined>,
  'addReview' : ActorMethod<[string, bigint, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelServiceRequest' : ActorMethod<[string, string, [] | [string]], undefined>,
  'completeJob' : ActorMethod<[string], undefined>,
  'createBooking' : ActorMethod<
    [string, string, string, string, [] | [string]],
    string
  >,
  'createServiceRequest' : ActorMethod<
    [string, string, string, string, [] | [number], [] | [number], [] | [string]],
    string
  >,
  'customerRespondToPrice' : ActorMethod<[string, boolean], undefined>,
  'getAllParts' : ActorMethod<[], Array<Part>>,
  'getAvailableMechanics' : ActorMethod<[], Array<Mechanic>>,
  'getBooking' : ActorMethod<[string], Booking>,
  'getCallerUserAppRole' : ActorMethod<[], string>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerActiveRequest' : ActorMethod<[], [] | [ServiceRequest]>,
  'getCustomerCompletedRequests' : ActorMethod<[], Array<ServiceRequest>>,
  'getMechanic' : ActorMethod<[string], Mechanic>,
  'getMechanicActiveJob' : ActorMethod<[], [] | [ServiceRequest]>,
  'getMechanicCompletedJobs' : ActorMethod<[], Array<ServiceRequest>>,
  'getMechanicPublicProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getMessages' : ActorMethod<[string], Array<ChatMessage>>,
  'getPart' : ActorMethod<[string], Part>,
  'getReviews' : ActorMethod<[string], Array<Review>>,
  'getSearchingRequests' : ActorMethod<[], Array<ServiceRequest>>,
  'getServiceRequests' : ActorMethod<[], Array<ServiceRequest>>,
  'getUserBookings' : ActorMethod<[], Array<Booking>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserAppRole' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedData' : ActorMethod<[], undefined>,
  'markMessagesRead' : ActorMethod<[string], undefined>,
  'sendMessage' : ActorMethod<[string, string], undefined>,
  'submitServicePrice' : ActorMethod<[string, bigint], undefined>,
  'updateBookingStatus' : ActorMethod<
    [
      string,
      { 'cancelled' : null } |
        { 'pending' : null } |
        { 'completed' : null } |
        { 'confirmed' : null },
    ],
    undefined
  >,
  'submitRating' : ActorMethod<[string, bigint, string], undefined>,
  'updateServiceRequest' : ActorMethod<
    [
      string,
      bigint,
      { 'price_sent' : null },
    ],
    undefined
  >,
  'updateServiceRequestStatus' : ActorMethod<
    [
      string,
      { 'on_the_way' : null } |
        { 'arrived' : null } |
        { 'completed' : null } |
        { 'accepted' : null },
    ],
    undefined
  >,
  'updateUserProfile' : ActorMethod<
    [[] | [string], [] | [string], [] | [bigint], [] | [string]],
    UserProfile
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
