/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ServiceRequest {
    id: string;
    customerName: string;
    status: Variant_on_the_way_cancelled_arrived_completed_approved_accepted_searching_price_sent;
    latitude?: number;
    serviceType: string;
    issueDescription: string;
    mechanicRating?: bigint;
    createdAt: Time;
    customerRating?: bigint;
    cancelledBy?: string;
    mechanicId?: Principal;
    longitude?: number;
    address?: string;
    mechanicName?: string;
    customerId: Principal;
    cancelReason?: string;
    price?: bigint;
    location: string;
}
export interface Part {
    id: string;
    inStock: boolean;
    isVerifiedSeller: boolean;
    name: string;
    description: string;
    sellerName: string;
    category: string;
    priceNGN: bigint;
}
export type Time = bigint;
export interface ChatMessage {
    id: string;
    requestId: string;
    createdAt: Time;
    isRead: boolean;
    message: string;
    senderRole: string;
    senderId: Principal;
}
export interface Booking {
    id: string;
    status: Variant_cancelled_pending_completed_confirmed;
    serviceType: string;
    scheduledDate: string;
    scheduledTime: string;
    userId: Principal;
    createdAt: Time;
    mechanicId: string;
    notes?: string;
}
export interface Mechanic {
    id: string;
    name: string;
    isAvailable: boolean;
    specialty: string;
    distanceKm: number;
    rating: number;
}
export interface UserProfile {
    totalRatings: bigint;
    latitude?: number;
    yearsOfExperience?: bigint;
    ratingsSum: bigint;
    userId: Principal;
    profileImage?: string;
    name: string;
    role?: string;
    longitude?: number;
    address?: string;
    specialties?: string;
    phone: string;
    location: string;
    verificationStatus?: string;
}
export interface Review {
    id: string;
    userId: Principal;
    text: string;
    mechanicId: string;
    timestamp: Time;
    rating: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_cancelled_pending_completed_confirmed {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export enum Variant_on_the_way_arrived_completed_accepted {
    on_the_way = "on_the_way",
    arrived = "arrived",
    completed = "completed",
    accepted = "accepted"
}
export enum Variant_on_the_way_cancelled_arrived_completed_approved_accepted_searching_price_sent {
    on_the_way = "on_the_way",
    cancelled = "cancelled",
    arrived = "arrived",
    completed = "completed",
    approved = "approved",
    accepted = "accepted",
    searching = "searching",
    price_sent = "price_sent"
}
export enum Variant_price_sent {
    price_sent = "price_sent"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptServiceRequest(requestId: string, mechanicName: string): Promise<void>;
    addReview(mechanicId: string, rating: bigint, text: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelServiceRequest(requestId: string, cancelledBy: string, reason: string | null): Promise<void>;
    completeJob(requestId: string): Promise<void>;
    createBooking(mechanicId: string, serviceType: string, scheduledDate: string, scheduledTime: string, notes: string | null): Promise<string>;
    createServiceRequest(customerName: string, location: string, issueDescription: string, serviceType: string, latitude: number | null, longitude: number | null, address: string | null): Promise<string>;
    customerRespondToPrice(requestId: string, accept: boolean): Promise<void>;
    getAllMechanics(): Promise<Array<UserProfile>>;
    getAllParts(): Promise<Array<Part>>;
    getAvailableMechanics(): Promise<Array<Mechanic>>;
    getBooking(bookingId: string): Promise<Booking>;
    getCallerUserAppRole(): Promise<string>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCustomerActiveRequest(): Promise<ServiceRequest | null>;
    getCustomerCompletedRequests(): Promise<Array<ServiceRequest>>;
    getMechanic(id: string): Promise<Mechanic>;
    getMechanicActiveJob(): Promise<ServiceRequest | null>;
    getMechanicCompletedJobs(): Promise<Array<ServiceRequest>>;
    getMechanicPublicProfile(mechanicId: Principal): Promise<UserProfile | null>;
    getMessages(requestId: string): Promise<Array<ChatMessage>>;
    getPart(id: string): Promise<Part>;
    getReviews(mechanicId: string): Promise<Array<Review>>;
    getSearchingRequests(): Promise<Array<ServiceRequest>>;
    getServiceRequests(): Promise<Array<ServiceRequest>>;
    getUserBookings(): Promise<Array<Booking>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markMessagesRead(requestId: string): Promise<void>;
    saveCallerUserAppRole(role: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedData(): Promise<void>;
    sendMessage(requestId: string, message: string): Promise<void>;
    submitRating(requestId: string, rating: bigint, raterRole: string): Promise<void>;
    submitServicePrice(requestId: string, price: bigint): Promise<void>;
    updateBookingStatus(bookingId: string, newStatus: Variant_cancelled_pending_completed_confirmed): Promise<void>;
    updateMechanicVerificationStatus(mechanicId: Principal, status: string): Promise<void>;
    updateServiceRequest(requestId: string, price: bigint, newStatus: Variant_price_sent): Promise<void>;
    updateServiceRequestStatus(requestId: string, newStatus: Variant_on_the_way_arrived_completed_accepted): Promise<void>;
    updateUserProfile(name: string | null, profileImage: string | null, yearsOfExperience: bigint | null, specialties: string | null): Promise<UserProfile>;
}
import type { Booking as _Booking, ServiceRequest as _ServiceRequest, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptServiceRequest(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptServiceRequest(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptServiceRequest(arg0, arg1);
            return result;
        }
    }
    async addReview(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addReview(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReview(arg0, arg1, arg2);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelServiceRequest(arg0: string, arg1: string, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelServiceRequest(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelServiceRequest(arg0, arg1, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async completeJob(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.completeJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.completeJob(arg0);
            return result;
        }
    }
    async createBooking(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(arg0, arg1, arg2, arg3, to_candid_opt_n3(this._uploadFile, this._downloadFile, arg4));
            return result;
        }
    }
    async createServiceRequest(arg0: string, arg1: string, arg2: string, arg3: string, arg4: number | null, arg5: number | null, arg6: string | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createServiceRequest(arg0, arg1, arg2, arg3, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg6));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createServiceRequest(arg0, arg1, arg2, arg3, to_candid_opt_n4(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n4(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg6));
            return result;
        }
    }
    async customerRespondToPrice(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.customerRespondToPrice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.customerRespondToPrice(arg0, arg1);
            return result;
        }
    }
    async getAllMechanics(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMechanics();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMechanics();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllParts(): Promise<Array<Part>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllParts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllParts();
            return result;
        }
    }
    async getAvailableMechanics(): Promise<Array<Mechanic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableMechanics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableMechanics();
            return result;
        }
    }
    async getBooking(arg0: string): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_Booking_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_Booking_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserAppRole(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserAppRole();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserAppRole();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerActiveRequest(): Promise<ServiceRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerActiveRequest();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerActiveRequest();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCustomerCompletedRequests(): Promise<Array<ServiceRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCustomerCompletedRequests();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCustomerCompletedRequests();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMechanic(arg0: string): Promise<Mechanic> {
        if (this.processError) {
            try {
                const result = await this.actor.getMechanic(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMechanic(arg0);
            return result;
        }
    }
    async getMechanicActiveJob(): Promise<ServiceRequest | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMechanicActiveJob();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMechanicActiveJob();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMechanicCompletedJobs(): Promise<Array<ServiceRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMechanicCompletedJobs();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMechanicCompletedJobs();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMechanicPublicProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMechanicPublicProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMechanicPublicProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: string): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0);
            return result;
        }
    }
    async getPart(arg0: string): Promise<Part> {
        if (this.processError) {
            try {
                const result = await this.actor.getPart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPart(arg0);
            return result;
        }
    }
    async getReviews(arg0: string): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReviews(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReviews(arg0);
            return result;
        }
    }
    async getSearchingRequests(): Promise<Array<ServiceRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSearchingRequests();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSearchingRequests();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getServiceRequests(): Promise<Array<ServiceRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getServiceRequests();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getServiceRequests();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBookings();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBookings();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markMessagesRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markMessagesRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markMessagesRead(arg0);
            return result;
        }
    }
    async saveCallerUserAppRole(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserAppRole(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserAppRole(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async seedData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.seedData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedData();
            return result;
        }
    }
    async sendMessage(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1);
            return result;
        }
    }
    async submitRating(arg0: string, arg1: bigint, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitRating(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitRating(arg0, arg1, arg2);
            return result;
        }
    }
    async submitServicePrice(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitServicePrice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitServicePrice(arg0, arg1);
            return result;
        }
    }
    async updateBookingStatus(arg0: string, arg1: Variant_cancelled_pending_completed_confirmed): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBookingStatus(arg0, to_candid_variant_n26(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBookingStatus(arg0, to_candid_variant_n26(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMechanicVerificationStatus(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMechanicVerificationStatus(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMechanicVerificationStatus(arg0, arg1);
            return result;
        }
    }
    async updateServiceRequest(arg0: string, arg1: bigint, arg2: Variant_price_sent): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateServiceRequest(arg0, arg1, to_candid_variant_n27(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateServiceRequest(arg0, arg1, to_candid_variant_n27(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateServiceRequestStatus(arg0: string, arg1: Variant_on_the_way_arrived_completed_accepted): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateServiceRequestStatus(arg0, to_candid_variant_n28(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateServiceRequestStatus(arg0, to_candid_variant_n28(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateUserProfile(arg0: string | null, arg1: string | null, arg2: bigint | null, arg3: string | null): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(to_candid_opt_n3(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n29(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3));
                return from_candid_UserProfile_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(to_candid_opt_n3(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n29(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n3(this._uploadFile, this._downloadFile, arg3));
            return from_candid_UserProfile_n6(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Booking_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceRequest_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceRequest): ServiceRequest {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n6(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ServiceRequest]): ServiceRequest | null {
    return value.length === 0 ? null : from_candid_ServiceRequest_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        cancelled: null;
    } | {
        pending: null;
    } | {
        completed: null;
    } | {
        confirmed: null;
    };
    serviceType: string;
    scheduledDate: string;
    scheduledTime: string;
    userId: Principal;
    createdAt: _Time;
    mechanicId: string;
    notes: [] | [string];
}): {
    id: string;
    status: Variant_cancelled_pending_completed_confirmed;
    serviceType: string;
    scheduledDate: string;
    scheduledTime: string;
    userId: Principal;
    createdAt: Time;
    mechanicId: string;
    notes?: string;
} {
    return {
        id: value.id,
        status: from_candid_variant_n13(_uploadFile, _downloadFile, value.status),
        serviceType: value.serviceType,
        scheduledDate: value.scheduledDate,
        scheduledTime: value.scheduledTime,
        userId: value.userId,
        createdAt: value.createdAt,
        mechanicId: value.mechanicId,
        notes: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.notes))
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    customerName: string;
    status: {
        on_the_way: null;
    } | {
        cancelled: null;
    } | {
        arrived: null;
    } | {
        completed: null;
    } | {
        approved: null;
    } | {
        accepted: null;
    } | {
        searching: null;
    } | {
        price_sent: null;
    };
    latitude: [] | [number];
    serviceType: string;
    issueDescription: string;
    mechanicRating: [] | [bigint];
    createdAt: _Time;
    customerRating: [] | [bigint];
    cancelledBy: [] | [string];
    mechanicId: [] | [Principal];
    longitude: [] | [number];
    address: [] | [string];
    mechanicName: [] | [string];
    customerId: Principal;
    cancelReason: [] | [string];
    price: [] | [bigint];
    location: string;
}): {
    id: string;
    customerName: string;
    status: Variant_on_the_way_cancelled_arrived_completed_approved_accepted_searching_price_sent;
    latitude?: number;
    serviceType: string;
    issueDescription: string;
    mechanicRating?: bigint;
    createdAt: Time;
    customerRating?: bigint;
    cancelledBy?: string;
    mechanicId?: Principal;
    longitude?: number;
    address?: string;
    mechanicName?: string;
    customerId: Principal;
    cancelReason?: string;
    price?: bigint;
    location: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_variant_n20(_uploadFile, _downloadFile, value.status),
        latitude: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.latitude)),
        serviceType: value.serviceType,
        issueDescription: value.issueDescription,
        mechanicRating: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.mechanicRating)),
        createdAt: value.createdAt,
        customerRating: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.customerRating)),
        cancelledBy: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.cancelledBy)),
        mechanicId: record_opt_to_undefined(from_candid_opt_n21(_uploadFile, _downloadFile, value.mechanicId)),
        longitude: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.longitude)),
        address: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.address)),
        mechanicName: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.mechanicName)),
        customerId: value.customerId,
        cancelReason: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.cancelReason)),
        price: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.price)),
        location: value.location
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalRatings: bigint;
    latitude: [] | [number];
    yearsOfExperience: [] | [bigint];
    ratingsSum: bigint;
    userId: Principal;
    profileImage: [] | [string];
    name: string;
    role: [] | [string];
    longitude: [] | [number];
    address: [] | [string];
    specialties: [] | [string];
    phone: string;
    location: string;
    verificationStatus: [] | [string];
}): {
    totalRatings: bigint;
    latitude?: number;
    yearsOfExperience?: bigint;
    ratingsSum: bigint;
    userId: Principal;
    profileImage?: string;
    name: string;
    role?: string;
    longitude?: number;
    address?: string;
    specialties?: string;
    phone: string;
    location: string;
    verificationStatus?: string;
} {
    return {
        totalRatings: value.totalRatings,
        latitude: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.latitude)),
        yearsOfExperience: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.yearsOfExperience)),
        ratingsSum: value.ratingsSum,
        userId: value.userId,
        profileImage: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.profileImage)),
        name: value.name,
        role: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.role)),
        longitude: record_opt_to_undefined(from_candid_opt_n8(_uploadFile, _downloadFile, value.longitude)),
        address: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.address)),
        specialties: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.specialties)),
        phone: value.phone,
        location: value.location,
        verificationStatus: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.verificationStatus))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): Variant_cancelled_pending_completed_confirmed {
    return "cancelled" in value ? Variant_cancelled_pending_completed_confirmed.cancelled : "pending" in value ? Variant_cancelled_pending_completed_confirmed.pending : "completed" in value ? Variant_cancelled_pending_completed_confirmed.completed : "confirmed" in value ? Variant_cancelled_pending_completed_confirmed.confirmed : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    on_the_way: null;
} | {
    cancelled: null;
} | {
    arrived: null;
} | {
    completed: null;
} | {
    approved: null;
} | {
    accepted: null;
} | {
    searching: null;
} | {
    price_sent: null;
}): Variant_on_the_way_cancelled_arrived_completed_approved_accepted_searching_price_sent {
    return "on_the_way" in value ? Variant_on_the_way_cancelled_arrived_completed_approved_accepted_searching_price_sent.on_the_way : "cancelled" in value ? Variant_on_the_way_cancelled_arrived_completed_approved_accepted_searching_price_sent.cancelled : "arrived" in value ? Variant_on_the_way_cancelled_arrived_completed_approved_accepted_searching_price_sent.arrived : "completed" in value ? Variant_on_the_way_cancelled_arrived_completed_approved_accepted_searching_price_sent.completed : "approved" in value ? Variant_on_the_way_cancelled_arrived_completed_approved_accepted_searching_price_sent.approved : "accepted" in value ? Variant_on_the_way_cancelled_arrived_completed_approved_accepted_searching_price_sent.accepted : "searching" in value ? Variant_on_the_way_cancelled_arrived_completed_approved_accepted_searching_price_sent.searching : "price_sent" in value ? Variant_on_the_way_cancelled_arrived_completed_approved_accepted_searching_price_sent.price_sent : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ServiceRequest>): Array<ServiceRequest> {
    return value.map((x)=>from_candid_ServiceRequest_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n6(_uploadFile, _downloadFile, x));
}
function to_candid_UserProfile_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: number | null): [] | [number] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalRatings: bigint;
    latitude?: number;
    yearsOfExperience?: bigint;
    ratingsSum: bigint;
    userId: Principal;
    profileImage?: string;
    name: string;
    role?: string;
    longitude?: number;
    address?: string;
    specialties?: string;
    phone: string;
    location: string;
    verificationStatus?: string;
}): {
    totalRatings: bigint;
    latitude: [] | [number];
    yearsOfExperience: [] | [bigint];
    ratingsSum: bigint;
    userId: Principal;
    profileImage: [] | [string];
    name: string;
    role: [] | [string];
    longitude: [] | [number];
    address: [] | [string];
    specialties: [] | [string];
    phone: string;
    location: string;
    verificationStatus: [] | [string];
} {
    return {
        totalRatings: value.totalRatings,
        latitude: value.latitude ? candid_some(value.latitude) : candid_none(),
        yearsOfExperience: value.yearsOfExperience ? candid_some(value.yearsOfExperience) : candid_none(),
        ratingsSum: value.ratingsSum,
        userId: value.userId,
        profileImage: value.profileImage ? candid_some(value.profileImage) : candid_none(),
        name: value.name,
        role: value.role ? candid_some(value.role) : candid_none(),
        longitude: value.longitude ? candid_some(value.longitude) : candid_none(),
        address: value.address ? candid_some(value.address) : candid_none(),
        specialties: value.specialties ? candid_some(value.specialties) : candid_none(),
        phone: value.phone,
        location: value.location,
        verificationStatus: value.verificationStatus ? candid_some(value.verificationStatus) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_cancelled_pending_completed_confirmed): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} {
    return value == Variant_cancelled_pending_completed_confirmed.cancelled ? {
        cancelled: null
    } : value == Variant_cancelled_pending_completed_confirmed.pending ? {
        pending: null
    } : value == Variant_cancelled_pending_completed_confirmed.completed ? {
        completed: null
    } : value == Variant_cancelled_pending_completed_confirmed.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_price_sent): {
    price_sent: null;
} {
    return value == Variant_price_sent.price_sent ? {
        price_sent: null
    } : value;
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_on_the_way_arrived_completed_accepted): {
    on_the_way: null;
} | {
    arrived: null;
} | {
    completed: null;
} | {
    accepted: null;
} {
    return value == Variant_on_the_way_arrived_completed_accepted.on_the_way ? {
        on_the_way: null
    } : value == Variant_on_the_way_arrived_completed_accepted.arrived ? {
        arrived: null
    } : value == Variant_on_the_way_arrived_completed_accepted.completed ? {
        completed: null
    } : value == Variant_on_the_way_arrived_completed_accepted.accepted ? {
        accepted: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
